services:
  - type: web
    name: dprojects
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
